on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    steps:
      - name: Working_dir
        id: step_1
        run: echo "my_variable=hola mundo" >> $GITHUB_OUTPUT
      - name: obtener mensaje
        run: echo "El mensaje es ${{ steps.step_1.outputs.my_variable }}"
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}
    steps:
      - name: hola mundo 2
        run: echo "El mensaje en el segundo job es $SALIDA"