on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo
        run: echo "Hola mundo"
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo 2
        run: echo "Hola mundo 2"