on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Working_dir
        run: ls -al
      - name: Action
        uses: actions/checkout@v4
      - name: working dir after action
        run: ls -al
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo 2
        run: echo "Hola mundo 2"