on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Working_dir
        id: step_1
        run: echo "my_variable=hola mundo" >> $GITHUB_OUTPUT
      - name: obtener mensaje
        run: echo "El mensaje es ${{ steps.step_1.outputs.my_variable }}"
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo 2
        run: echo "Hola mundo 2"